[package]
name = "port_sniffer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.29", features = ["full"] }
indicatif = "0.18.0"